#!/bin/bash
# Git Hooks Installation Script
#
# This script installs pre-commit framework hooks to enforce repository standards.
# Run this script after cloning the repository:
#   bash scripts/git-hooks/install.sh
#
# Or if using as a submodule:
#   bash docs/standards/scripts/git-hooks/install.sh

set -e

# ANSI color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}   Git Hooks Installation${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Get the repository root directory
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

install_post_commit_audit_hook() {
  local post_commit_hook="$REPO_ROOT/.git/hooks/post-commit"

  cat > "$post_commit_hook" <<'POSTEOF'
#!/usr/bin/env bash
# File generated by scripts/git-hooks/install.sh
# Post-commit audit: logs when --no-verify likely bypassed doc enforcement.
set +e

REPO_ROOT="$(git rev-parse --show-toplevel)"

# Try standard location first, then submodule location
for AUDIT_SCRIPT in \
  "$REPO_ROOT/scripts/git-hooks/post-commit-audit" \
  "$REPO_ROOT/docs/standards/scripts/git-hooks/post-commit-audit"; do
  if [[ -f "$AUDIT_SCRIPT" ]]; then
    exec bash "$AUDIT_SCRIPT"
  fi
done
POSTEOF
  chmod +x "$post_commit_hook"
}

if ! command -v pre-commit >/dev/null 2>&1; then
  echo -e "${YELLOW}✗ pre-commit is not installed.${NC}"
  echo -e "${BLUE}Installing post-commit audit hook (native fallback)...${NC}"
  install_post_commit_audit_hook
  echo -e "${GREEN}✓${NC} post-commit audit installed (.git/hooks/post-commit)"
  echo ""
  echo -e "${BLUE}Install pre-commit for full commit-time checks:${NC}"
  echo -e "  pip install pre-commit"
  echo -e "  # or"
  echo -e "  uv tool install pre-commit"
  exit 0
fi

echo -e "${GREEN}✓${NC} Installing pre-commit hook..."
pre-commit install

# Force pre-commit to scan the entire repository on each commit.
# pre-commit does not provide an install flag for this behavior, so we rewrite
# the generated hook as a wrapper around `pre-commit run --all-files`.
PRE_COMMIT_HOOK="$REPO_ROOT/.git/hooks/pre-commit"
if [ -f "$PRE_COMMIT_HOOK" ]; then
  INSTALL_PYTHON_PATH="$(sed -n 's/^INSTALL_PYTHON=//p' "$PRE_COMMIT_HOOK" | head -n 1)"
  if [ -z "$INSTALL_PYTHON_PATH" ]; then
    INSTALL_PYTHON_PATH="$(command -v python3 || true)"
  fi

  cat > "$PRE_COMMIT_HOOK" <<EOF
#!/usr/bin/env bash
# File generated by scripts/git-hooks/install.sh
# Runs pre-commit checks against all tracked files on each commit.

INSTALL_PYTHON="$INSTALL_PYTHON_PATH"
ARGS=(run --all-files --hook-stage pre-commit --config=.pre-commit-config.yaml)

if [ -n "\$INSTALL_PYTHON" ] && [ -x "\$INSTALL_PYTHON" ]; then
    exec "\$INSTALL_PYTHON" -mpre_commit "\${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "\${ARGS[@]}"
else
    echo 'pre-commit not found. Did you forget to install it?' 1>&2
    exit 1
fi
EOF
  chmod +x "$PRE_COMMIT_HOOK"
fi

echo -e "  ${BLUE}→${NC} Runs repo hooks on every commit (all tracked files)"

echo -e "${GREEN}✓${NC} Installing post-commit audit hook..."
install_post_commit_audit_hook
echo -e "  ${BLUE}→${NC} Logs bypassed documentation enforcement"

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✓ Git hooks installed successfully!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}What these hooks do:${NC}"
echo -e "  • ${GREEN}pre-commit${NC}: Runs documentation enforcement + markdownlint"
echo -e "  • ${GREEN}post-commit${NC}: Audits --no-verify bypasses"
echo ""
echo -e "${BLUE}To bypass a hook in emergencies:${NC}"
echo -e "  git commit --no-verify"
echo ""
echo -e "${YELLOW}Note: Bypassing hooks should only be done when absolutely necessary.${NC}"
echo -e "${YELLOW}      Bypasses are logged to .git/doc-enforcement-audit.log${NC}"
echo ""
